[workspace]
resolver = "2"
members = ["crates/shared", "crates/server", "crates/client"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
glam = { version = "0.29", features = ["serde"] }

[profile.release]
opt-level = 2
lto = "thin"
